<Caja_color_box>:
    size_hint_y: None
    height: dp(10)
    orientation:"horizontal"
    padding:[1,]
    spacing: dp(2)
    Colorbox:
        id: colorbox
        colors_id: 0,0,0,0
        colors: self.colors_id
    MDLabel:
        size_hint_y:None
        height: dp(5)
        id: preciobox
        halign: "right"
        text: "" 
        theme_text_color: "Custom"
        text_color: 1,1,1,1